name: Trigger Netlify Build

on:
  schedule:
    - cron: '0 12 * * *'  # 8:00 AM ET (12:00 UTC)
  workflow_dispatch:

jobs:
  trigger-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build hook
        run: |
          curl -X POST https://api.netlify.com/build_hooks/68348ece6986883b973a90ef
